version: '3.3'
services:
  es:
    build: docker-container
    container_name: learn-es01
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
